"""Alert DB Model."""
from datetime import datetime, timezone
from sqlalchemy import Integer, String, Float, Boolean, DateTime, ForeignKey, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship
from typing import TYPE_CHECKING, Optional

from app.core.database import Base

if TYPE_CHECKING:
    from app.models.consumer import Consumer
    from app.models.inspection import Inspection


class Alert(Base):
    """Theft detection alert generated by dual-engine evaluation."""
    __tablename__ = "alerts"

    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    alert_id: Mapped[str] = mapped_column(String(64), unique=True, index=True)
    consumer_id: Mapped[str] = mapped_column(String(64), ForeignKey("consumers.consumer_id", ondelete="CASCADE"), index=True)
    
    # Engine scores
    risk_score: Mapped[float] = mapped_column(Float, nullable=False)  # Supervised P(Theft)
    anomaly_score: Mapped[float] = mapped_column(Float, nullable=False)  # IsolationForest score
    feeder_loss_factor: Mapped[float] = mapped_column(Float, default=0.0)  # Mass-balance residual loss factor
    composite_priority: Mapped[float] = mapped_column(Float, nullable=False)  # 0 - 100
    risk_tier: Mapped[str] = mapped_column(String(16), nullable=False)  # LOW, MEDIUM, HIGH, CRITICAL

    # Loss estimation (bounds & yield)
    estimated_unbilled_kwh: Mapped[float] = mapped_column(Float, default=0.0)
    estimated_loss_currency: Mapped[float] = mapped_column(Float, default=0.0)
    loss_lower_bound_95: Mapped[float] = mapped_column(Float, default=0.0)
    loss_upper_bound_95: Mapped[float] = mapped_column(Float, default=0.0)
    net_roi_yield: Mapped[float] = mapped_column(Float, default=0.0)

    # Directive & Explanations
    recommended_action: Mapped[str] = mapped_column(String(64), nullable=False)
    # PRIORITY_PHYSICAL_RAID, METER_CALIBRATION_TEST, REMOTE_FIRMWARE_AUDIT, WATCHLIST_7_DAY_MONITOR
    security_escort_required: Mapped[bool] = mapped_column(Boolean, default=False)
    plain_language_explanation: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    shap_feature_importance: Mapped[Optional[str]] = mapped_column(Text, nullable=True)  # JSON-encoded
    hardware_tamper_evidence: Mapped[str] = mapped_column(String(128), default="NORMAL")
    status: Mapped[str] = mapped_column(String(32), default="ACTIVE")  # ACTIVE, INSPECTED, RESOLVED, DISMISSED
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), default=lambda: datetime.now(timezone.utc)
    )

    consumer: Mapped["Consumer"] = relationship("Consumer", back_populates="alerts")
    inspection: Mapped[Optional["Inspection"]] = relationship("Inspection", back_populates="alert", uselist=False)
